_BASE_: "queryrcnn.cascade.res50.100pro.3x.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  # WEIGHTS: "/data/yu/code/OW-DETR/dino_resnet50_pretrain.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    # NUM_CLASSES: 21
    # TEST_TOPK: 100
  DISTILL:
    ENABLE: True
    BACKBONE: True
DATASETS:
  TRAIN: ('t3_voc_coco_2007_train', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', ) # voc_coco_2007_test, t1_voc_coco_2007_test, t1_voc_coco_2007_val
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00005
  STEPS: (24000, 32000)
  MAX_ITER: 36000
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 10000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "./output/t1"
OWOD:
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20
TEST:
  EVAL_PERIOD: 6001
